### ISSUE TITLE
timetrial/best/ and timetrial/best/current/ returns Server Error

### ISSUE THREAD

**Issue by Sobuno** [TK-IT/kasse#35]
https://enkasseienfestforening.dk/timetrial/best/ and https://enkasseienfestforening.dk/timetrial/best/current/ both return Server error

**Comment by Mortal** [comment]
Thanks - fixed in c67284e.

I've also added a custom view for Internal Server Error that prints an exception traceback. This should make it easier to fix crashes like this in the future.
